### ISSUE TITLE
Building on Mac

### ISSUE THREAD

**Issue by ElDiemo** [kodycode/CoinMarketDiscordBot#13]
Hello,

could you please help me with building CoinMarketDiscordBot on Mac.
I have installed python3. What is needed steps now? Please describe it for absolute noob in python.
I tried to run command pip install -r requirements.txt but it's not working and also modules missing.
like:

1. open terminal
2. type ..... to select folder with build
3. download coinmarketapi and store them .. 
4. install coinmarket api by command ..

Thank you very much

**Comment by kodycode** [comment]
I'm assuming the issue lies with not having pip installed properly. If you type just ```pip``` in the terminal, does it complain about not having it or does it mention commands you can input?

Also, there's no kind of build or compiling needed when trying to run this bot. Just run bot.py with ```python bot.py``` or rather, ```python3 bot.py``` specifically since I think OSX would prefer it that way.

**Comment by ElDiemo** [comment]
When typing pip I have these result:

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> NameError: name 'pip3' is not defined

when pip install -r requirements.txt these:
>   File "<stdin>", line 1
>     pip install -r requirements.txt
>               ^
> SyntaxError: invalid syntax

and when python bot.py:
Traceback (most recent call last):
  File "/Users/Tomas/Documents/Electra/bot.py", line 1, in <module>
    from discord.ext import commands
ModuleNotFoundError: No module named 'discord'

Thank you

**Comment by kodycode** [comment]
The second error is due to pip not installing the requirements.

Could you try actually installing pip via this command:
```
brew postinstall python3
```

The postinstall should give you pip..

If that doesn't work, try this to install the requirements:
```
python3 -m pip install -r requirements.txt
```

**Comment by kodycode** [comment]
Closed this issue assuming OP does not need help anymore.
